### ISSUE TITLE
How does Paket keep track of which packages are installed?

### ISSUE THREAD

**Issue by martisj** [joseluisq/paket#11]

**Comment by joseluisq** [comment]
For `paket`, packages are just git repositories placed in your home directory under the paket dir. E.g `~/.config/paket/user-name/package-name` and `paket` operates using git commands like `clone`, `fetch`, `pull`, etc. That's it.

If you are more curious then you can explore the [`src/paket.rs`](https://github.com/joseluisq/paket/blob/master/src/paket.rs#L73) or [`src/git.rs`](https://github.com/joseluisq/paket/blob/master/src/git.rs) files for example.
